#!/bin/bash


cat output/history/SM007001.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007001,ICICI PRUDENTIAL PENSION FUND SCHEME E - TIER I,/' > csv-output-mergable/SM007001.csv

cat output/history/SM007002.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007002,ICICI PRUDENTIAL PENSION FUND SCHEME C - TIER I,/' > csv-output-mergable/SM007002.csv

cat output/history/SM007003.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007003,ICICI PRUDENTIAL PENSION FUND SCHEME G - TIER I,/' > csv-output-mergable/SM007003.csv

cat output/history/SM007004.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007004,ICICI PRUDENTIAL PENSION FUND SCHEME E - TIER II,/' > csv-output-mergable/SM007004.csv

cat output/history/SM007005.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007005,ICICI PRUDENTIAL PENSION FUND SCHEME C - TIER II,/' > csv-output-mergable/SM007005.csv

cat output/history/SM007006.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007006,ICICI PRUDENTIAL PENSION FUND SCHEME G - TIER II,/' > csv-output-mergable/SM007006.csv

cat output/history/SM007007.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007007,NPS TRUST A\/C-ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED- NPS LITE SCHEME - GOVT. PATTERN,/' > csv-output-mergable/SM007007.csv

cat output/history/SM007008.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007008,ICICI PRUDENTIAL PENSION FUND SCHEME A - TIER I,/' > csv-output-mergable/SM007008.csv

cat output/history/SM007009.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007009,ICICI PRUDENTIAL PENSION FUND SCHEME A - TIER II,/' > csv-output-mergable/SM007009.csv

cat output/history/SM007010.csv | sed 's/,/,PFM007,ICICI PRUDENTIAL PENSION FUNDS MANAGEMENT COMPANY LIMITED,SM007010,ICICI PRUDENTIAL PENSION FUNDS SCHEME TAX SAVER TIER II,/' > csv-output-mergable/SM007010.csv



